CREATE TABLE BO_USERS.GENDERS (
	ID INTEGER  PRIMARY KEY NOT NULL,
	NAME VARCHAR2(150) NOT NULL,
	DESCRIPTION VARCHAR2(255) NULL,
	STATUS INTEGER NOT NULL,
	REGISTRATION_DATE TIMESTAMP NOT NULL,
	REGISTRATION_USER INTEGER NOT NULL,
	UPDATE_DATE TIMESTAMP NULL,
	UPDATE_USER INTEGER NULL,
	DISABLE_DATE TIMESTAMP NULL,
	DISABLE_USER INTEGER NULL
);

CREATE SEQUENCE BO_USERS.GENDERS_SEQ
START WITH 1
	MAXVALUE 999999999
	MINVALUE 1
CYCLE
NOCACHE
NOORDER;

ALTER TABLE GENDERS ADD CONSTRAINT UK_GENDER_NAME UNIQUE(NAME);

INSERT INTO BO_USERS.GENDERS (ID, NAME, DESCRIPTION, STATUS, REGISTRATION_DATE, REGISTRATION_USER) VALUES (1, 'MASCULINO', 'Hombres', 1, CURRENT_TIMESTAMP , 1);
INSERT INTO BO_USERS.GENDERS (ID, NAME, DESCRIPTION, STATUS, REGISTRATION_DATE, REGISTRATION_USER) VALUES (2, 'FEMENINO', 'Mujer', 1, CURRENT_TIMESTAMP, 1);